---
spring.profiles: postgres

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/impact}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

---
spring.profiles: mysql

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/impact}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
